### Đăng nhập
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
    "username" : "dangthanhtuan",
    "password" : "123456"
}

### Đăng ký
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "username" : "dangthanhtuan",
    "password" : "123456"
}

### Lấy profile
GET http://localhost:3000/api/users/me
token: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZTg4NWQzZTVlOTk4YzM0NDhlZThlMmUiLCJpYXQiOjE1ODczNzQwMzUsImV4cCI6MTU4Nzk3ODgzNX0.ekm8hSBokhxa_SqkRxhV9KUaOMU5jNPnESNZl5-e9q4

### Cập nhật profile
PATCH  http://localhost:3000/api/users/me
Content-Type: application/json
token: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZTlkOTMyODY2Y2YwODFmYWMwM2Q1ZWUiLCJpYXQiOjE1ODczODUxNTksImV4cCI6MTU4Nzk4OTk1OX0.CM2StejAGUgTXzjHoaF7bSVvovONjM4VsJv_6Z8w1pg

{
    "display_name": "Đặng Thanh Tuấn",
    "email": "contact.dangthanhtuan@gmail.com",
    "date_of_birth": "12/09/1997",
    "gender": "male"
}

### Tạo voucher
POST http://localhost:3000/api/vouchers
Content-Type: application/json
token: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZTg4NWQzZTVlOTk4YzM0NDhlZThlMmUiLCJpYXQiOjE1ODczNzQwMzUsImV4cCI6MTU4Nzk3ODgzNX0.ekm8hSBokhxa_SqkRxhV9KUaOMU5jNPnESNZl5-e9q4

{
    "partner_id" : "5e86e6a3e1ad0f44f494e825",
    "discount" : "10",
    "description" : "Giảm 20% tổng hóa đơn",
    "start_time" : "2020/01/01",
    "end_time" : "2020/12/31",
    "promo_code": "TOCO",
    "count": "10"
}

### Thêm người nhận vào thông tin voucher
POST http://localhost:3000/api/partners/5e86e6a3e1ad0f44f494e825/voucher
Content-Type: application/json
token: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZTg4NWQzZTVlOTk4YzM0NDhlZThlMmUiLCJpYXQiOjE1ODczNzQwMzUsImV4cCI6MTU4Nzk3ODgzNX0.ekm8hSBokhxa_SqkRxhV9KUaOMU5jNPnESNZl5-e9q4

{
    "user_id" : "5e9d932866cf081fac03d5ee"
}

### Lấy thông tin voucher
GET http://localhost:3000/api/vouchers/5e9d9ead4a6a632490cf2cdb
token: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZTg4NWQzZTVlOTk4YzM0NDhlZThlMmUiLCJpYXQiOjE1ODczNzQwMzUsImV4cCI6MTU4Nzk3ODgzNX0.ekm8hSBokhxa_SqkRxhV9KUaOMU5jNPnESNZl5-e9q4
