POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username" : "nguyensivan",
    "password" : "123456"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username" : "nguyensivan",
    "name": "Nguyễn Sĩ Văn",
    "email": "nguyensivan1998@gmail.com",
    "dateOfBirth": "11/04/1998",
    "gender": "female",
    "password" : "123456",
    "confirmPassword": "123456"
}

###
GET http://localhost:3000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW1hZ2UiOiIvdXBsb2Fkcy9kZWZhdWx0X2F2YXRhci5wbmciLCJyb2xlIjoidXNlciIsIl9pZCI6IjVlODZhZWQ5NTY0MTVjNDY1NDc0MTZjZSIsInVzZXJuYW1lIjoibmd1eWVuc2l2YW4xIiwibmFtZSI6Ik5ndXnhu4VuIFPEqSBWxINuIiwiZW1haWwiOiJuZ3V5ZW5zaXZhbjE5OThAZ21haWwuY29tIiwiZGF0ZU9mQmlydGgiOiIxMS8wNC8xOTk4Iiwic2V4IjoibnUiLCJjcmVhdGVkQXQiOiIyMDIwLTA0LTAzVDAzOjM0OjQ5Ljk3OVoiLCJ1cGRhdGVkQXQiOiIyMDIwLTA0LTAzVDAzOjM0OjQ5Ljk3OVoiLCJfX3YiOjAsImlhdCI6MTU4NTg4NDg5NiwiZXhwIjoxNTg2NDg5Njk2fQ.hx_DaWRIcsXnDDWF1W00yx58zQdUdV0T4MoM2wzxdPg

###
POST http://localhost:3000/api/users/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW1hZ2UiOiIvdXBsb2Fkcy9kZWZhdWx0X2F2YXRhci5wbmciLCJyb2xlIjoidXNlciIsIl9pZCI6IjVlODZhZWQ5NTY0MTVjNDY1NDc0MTZjZSIsInVzZXJuYW1lIjoibmd1eWVuc2l2YW4xIiwibmFtZSI6Ik5ndXnhu4VuIFPEqSBWxINuIiwiZW1haWwiOiJuZ3V5ZW5zaXZhbjE5OThAZ21haWwuY29tIiwiZGF0ZU9mQmlydGgiOiIxMS8wNC8xOTk4Iiwic2V4IjoibnUiLCJjcmVhdGVkQXQiOiIyMDIwLTA0LTAzVDAzOjM0OjQ5Ljk3OVoiLCJ1cGRhdGVkQXQiOiIyMDIwLTA0LTAzVDAzOjM0OjQ5Ljk3OVoiLCJfX3YiOjAsImlhdCI6MTU4NTg4NDg5NiwiZXhwIjoxNTg2NDg5Njk2fQ.hx_DaWRIcsXnDDWF1W00yx58zQdUdV0T4MoM2wzxdPg

{
    "_id" : "5e86aed956415c46547416ce",
    "username" : "nguyensivan",
    "name": "Nguyễn Sĩ Văn",
    "email": "nguyensivan1998@gmail.com",
    "dateOfBirth": "11/04/1997",
    "sex": "nu",
    "newPassword" : "123456",
    "confirmNewPassword": "123456"
}